//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.0
//     from Assets/Development/Prefabs/Game Management/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Dialogue"",
            ""id"": ""de396bac-c3a7-43f4-93f2-4d361a8bf6ef"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""053b44bb-f407-4d4d-a0a6-97ef694df359"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change Selection"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c5a08cf9-d320-46c6-850c-fa21e327155a"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""8a9196ac-13e1-4851-a4d9-3ba9334e90a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""82945459-0420-44b5-901d-f3bad80dd277"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4079a6ad-52f0-4c3e-a336-042decfa5886"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Left Stick"",
                    ""id"": ""01f86c26-0eeb-4a22-b898-87615aa199fd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5d9ccf04-5d12-4c7b-a24f-31755d279116"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a7ffc1af-92a0-4f7a-baaf-349b75752b29"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2724f3b1-4351-4d28-b9ea-ed0fdd88dc32"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""28713d0f-f21d-4af1-948b-d19f8c133d35"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""399a85d3-b3a2-47b3-96ff-8d82724a0116"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""71ae3f31-8825-4cd2-9e23-74d614863ba3"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""77fce446-56a9-4040-8123-f2359179f728"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7f36d9b5-eea4-4ff7-952c-0a9f8a8c131f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8c641a79-01b2-4f0f-b552-6ebcf444aece"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f3b3f033-1e90-472f-b9c3-06b985a58f17"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""444c6a2f-c56f-42bf-85d6-6ede5a879ecc"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Selector"",
            ""id"": ""e035308a-d628-4d92-87a0-6d9f43ca2995"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4f1ac0f0-8bea-419e-bc15-874fa8bb6215"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Skill Wheel"",
                    ""type"": ""Button"",
                    ""id"": ""a49a1b34-29a8-4f19-8116-81bc2e0ef642"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""c604108f-2008-4423-afb4-aff394b61d80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeSelect"",
                    ""type"": ""Button"",
                    ""id"": ""611c6732-58bd-4edc-aedb-384f9493641b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""79830cb1-299c-4570-a5b6-c14c9425080c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e20c256c-d68c-417a-ad50-e121136bf15c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2a990db1-5535-416c-a31f-87d2d322fc4f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3783771e-562a-4fa2-94e7-db41848d82af"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5cf0c37e-9dbc-43ee-b7de-ddeb88d728e0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left JoyStick"",
                    ""id"": ""f09ee884-35df-47d1-93d8-2a2af18cc340"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6dc47d5e-fc2a-42f8-85be-b3d85ecb0784"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""75d2e3ba-586e-451a-b577-97fbf2ef99db"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""84dc7715-232c-4628-97eb-1b7e34c6efbc"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""58439aaf-2dd7-461a-96d5-4f28eecd4dec"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""43c083c6-1084-4071-bc65-bb248ecd5607"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Skill Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""908904ac-349a-4563-84a7-dbd01bad885e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e32a94f-ceac-4990-b806-2a8f03b27930"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""68a5057e-ccca-4126-b93c-6ac885b0b0d8"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""52fd0acd-02c5-4330-99f3-9e56313d06ab"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""5c672ab5-4898-4785-b7c6-1c63f8407f5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a2fe85a6-d37c-45b4-ae4d-135093600209"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""ScaleVector2(x=0.0625,y=0.0625),NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""752664f3-3332-45c6-8089-aab09c323148"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2,StickDeadzone(min=0.01)"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Skill Wheel"",
                    ""type"": ""Button"",
                    ""id"": ""ec6c4732-f5e7-4bf5-9111-3603ad942e20"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Restart Level"",
                    ""type"": ""Button"",
                    ""id"": ""480fe164-1fd1-4253-a9de-38cb4d7078d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleAiming"",
                    ""type"": ""Button"",
                    ""id"": ""bf17801b-ac06-4635-b41d-0fbd7c990a34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Use Agility"",
                    ""type"": ""Button"",
                    ""id"": ""b8437d5c-e8b9-49e3-ab40-1241bb4532db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Weapon 1"",
                    ""type"": ""Button"",
                    ""id"": ""878ac51a-f2d7-40e4-877e-1c1eb7ee7e2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Weapon 2"",
                    ""type"": ""Button"",
                    ""id"": ""06449f62-29b1-4d4c-a25f-7369c7feeaf8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Ability 1"",
                    ""type"": ""Button"",
                    ""id"": ""b588de10-e478-4cb1-8004-b61ebe494638"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Ability 2"",
                    ""type"": ""Button"",
                    ""id"": ""ec74ea63-2abd-437e-95e9-fce34bdaadf2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Character Left"",
                    ""type"": ""Button"",
                    ""id"": ""599251ad-20f4-467b-9fa5-9bd032b8cfff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Character Right"",
                    ""type"": ""Button"",
                    ""id"": ""914090a5-f3c3-4d72-863a-4189de3f5259"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Restart Level1"",
                    ""type"": ""Button"",
                    ""id"": ""597c9b68-87bb-43d9-bf2e-aae16e08459c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Controls"",
                    ""type"": ""Button"",
                    ""id"": ""62e0296d-8e52-4702-b2b3-7bb1c9482ef4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""d6e1f443-df26-43a2-94fd-ca2652f3d061"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f9f60b97-a876-4dca-a1b7-100e0efb5a7c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""53b73e7b-0068-4ad0-9776-24106767ec19"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""09ba677a-2158-4ae4-9c51-a48d5e544edb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""12daa01d-564f-4dba-9797-1862a13c2fe0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left JoyStick"",
                    ""id"": ""d4042272-c096-4bed-9c52-7384706a276f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""09091793-3b87-4f02-97e7-222f12b0f6b7"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f1ab8222-28e3-4c38-b542-b67b81632c87"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b71cb92a-14e8-4afe-8c32-1c4e9044547a"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8f7b6f19-6c36-4c4c-9021-2f1359c99f16"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a40fb0d0-6b67-4aa2-8acb-2e37bf919697"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe83c44d-57d1-427e-bd70-8c81d7b7a7bd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""5e528783-b6b7-429f-8f51-6ecf431f6aaf"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1b13bf43-3d00-43c4-8fcb-938586307806"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9ddb4f4b-4b61-4d10-9575-b6dcf4f2d5f9"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3581aa4f-ee5e-4d6b-bb52-71af9fc2279a"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7dc5dd47-4cfc-455a-a097-465b03544403"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""id"": ""ee15e431-15bc-4584-b858-68b8403211cb"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0a16b71c-82b1-44f4-a450-740aa0e0ecdd"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7c28c466-7af6-4d23-9e89-13a21012c184"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dd2f4491-aee0-4583-9576-38734e72f9f0"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8495f449-9c20-4db7-bed2-c64ad19596e7"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""048b29f1-0453-4dae-a360-fe17e7080c3e"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cfcc461f-0fa1-49e9-8c07-b4bcb69631c7"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6435c318-3de7-432d-a37e-95ac061e21f4"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e631d459-3d98-4841-8037-eaf0ad2241ab"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8662b792-3779-4298-bbb1-3b2c8ea0ab87"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""id"": ""2c3a624d-15ca-4595-8acd-5656509019f3"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1d4de741-4ef3-4404-8d26-3bebaaf34601"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f5195376-4f78-4849-8042-5b565ece43b2"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""93b9525f-c565-4c25-9c41-2748795940be"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""65f55479-36a2-4560-99a7-cbd532255291"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2a82d6b1-5592-4f6b-83f1-dbf73d8f9c81"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Skill Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17e5ff58-b8a6-4dbb-9f2b-d5cd99943db9"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Skill Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2515ca30-ba1d-409b-b144-ea996f296318"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart Level"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2455dbb4-f497-4842-a92c-05e21ec8fb54"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart Level"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2572c5c-da73-4128-8880-73e4d760d014"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleAiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d671848-b3a4-46aa-b1d3-f45eac3ae668"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleAiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18aab23a-4af3-4cb5-8a86-7eeb5969c547"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Weapon 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6e9ab7a-0109-4d1f-806f-ac723cfc35ef"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Weapon 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da067128-eadc-4233-8c0b-09384dcc7cff"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Weapon 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbb8395e-0133-407f-8ba9-75999d2ce681"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Weapon 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a79c5e7-833f-436b-8743-48280dfff18c"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Ability 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fa93bc9-251d-4832-bbbc-0c0b98169afc"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Ability 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3aa9cd48-11c1-4653-9564-ae244285b400"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Agility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cb3c07e-00c2-4e64-9722-e4190aa44a48"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Agility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00cd1f8e-662c-4511-bd24-f458ed0da090"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6d9521a-8bb7-4de1-902d-201cbf3909ab"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3771b18-44cd-4442-b027-dbf50b7ae38f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b75879b0-e0d7-4f3c-8a2f-299b73a55ede"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fad8c3dc-5d7e-46f3-b0e8-2369fa7b11f4"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Ability 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""789e97c3-e678-4b56-859a-55537c2b5604"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Ability 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd455edf-bfb9-4f8d-91b9-e536e97897fb"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart Level1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef7340a8-1f35-4374-b041-832db0c58479"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Controls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""636e8e47-f019-4ae1-b356-3a99a0b0929c"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Controls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Dismiss"",
            ""id"": ""3a63b7db-9d1e-4cdd-ba64-15d88c346430"",
            ""actions"": [
                {
                    ""name"": ""Dismiss"",
                    ""type"": ""Button"",
                    ""id"": ""ab51f92b-6b0b-4984-8b23-101b40f9ed23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""466e80ad-72ff-4a32-9f0c-9628c700cd3a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dismiss"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""094e97e3-d4ab-4e09-bff8-41ae45d11071"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dismiss"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""1228cef1-8522-4fec-bbb1-e70928a9b061"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""d4bc3486-1711-4e2d-a402-a1c535c6c9d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""62f08b74-2a7f-4119-85f5-0444712ae48a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""03ee2d9a-54c9-4ba7-9a23-9e5bf2bdbe62"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42116508-a709-49ee-b5ce-7d38cb1745fe"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b419ab3-2d8d-468a-a6a8-bbc64a346dfb"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06d8d3a9-a9e0-4fdd-b60b-d40b3cac8cd0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Dialogue
        m_Dialogue = asset.FindActionMap("Dialogue", throwIfNotFound: true);
        m_Dialogue_Continue = m_Dialogue.FindAction("Continue", throwIfNotFound: true);
        m_Dialogue_ChangeSelection = m_Dialogue.FindAction("Change Selection", throwIfNotFound: true);
        m_Dialogue_Back = m_Dialogue.FindAction("Back", throwIfNotFound: true);
        // Selector
        m_Selector = asset.FindActionMap("Selector", throwIfNotFound: true);
        m_Selector_Move = m_Selector.FindAction("Move", throwIfNotFound: true);
        m_Selector_ToggleSkillWheel = m_Selector.FindAction("Toggle Skill Wheel", throwIfNotFound: true);
        m_Selector_Select = m_Selector.FindAction("Select", throwIfNotFound: true);
        m_Selector_DeSelect = m_Selector.FindAction("DeSelect", throwIfNotFound: true);
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Aim = m_Player.FindAction("Aim", throwIfNotFound: true);
        m_Player_ToggleSkillWheel = m_Player.FindAction("Toggle Skill Wheel", throwIfNotFound: true);
        m_Player_RestartLevel = m_Player.FindAction("Restart Level", throwIfNotFound: true);
        m_Player_ToggleAiming = m_Player.FindAction("ToggleAiming", throwIfNotFound: true);
        m_Player_UseAgility = m_Player.FindAction("Use Agility", throwIfNotFound: true);
        m_Player_UseWeapon1 = m_Player.FindAction("Use Weapon 1", throwIfNotFound: true);
        m_Player_UseWeapon2 = m_Player.FindAction("Use Weapon 2", throwIfNotFound: true);
        m_Player_UseAbility1 = m_Player.FindAction("Use Ability 1", throwIfNotFound: true);
        m_Player_UseAbility2 = m_Player.FindAction("Use Ability 2", throwIfNotFound: true);
        m_Player_SwitchCharacterLeft = m_Player.FindAction("Switch Character Left", throwIfNotFound: true);
        m_Player_SwitchCharacterRight = m_Player.FindAction("Switch Character Right", throwIfNotFound: true);
        m_Player_RestartLevel1 = m_Player.FindAction("Restart Level1", throwIfNotFound: true);
        m_Player_ToggleControls = m_Player.FindAction("Toggle Controls", throwIfNotFound: true);
        // Dismiss
        m_Dismiss = asset.FindActionMap("Dismiss", throwIfNotFound: true);
        m_Dismiss_Dismiss = m_Dismiss.FindAction("Dismiss", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_Select = m_Menu.FindAction("Select", throwIfNotFound: true);
        m_Menu_Cancel = m_Menu.FindAction("Cancel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Dialogue
    private readonly InputActionMap m_Dialogue;
    private List<IDialogueActions> m_DialogueActionsCallbackInterfaces = new List<IDialogueActions>();
    private readonly InputAction m_Dialogue_Continue;
    private readonly InputAction m_Dialogue_ChangeSelection;
    private readonly InputAction m_Dialogue_Back;
    public struct DialogueActions
    {
        private @PlayerControls m_Wrapper;
        public DialogueActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Continue => m_Wrapper.m_Dialogue_Continue;
        public InputAction @ChangeSelection => m_Wrapper.m_Dialogue_ChangeSelection;
        public InputAction @Back => m_Wrapper.m_Dialogue_Back;
        public InputActionMap Get() { return m_Wrapper.m_Dialogue; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogueActions set) { return set.Get(); }
        public void AddCallbacks(IDialogueActions instance)
        {
            if (instance == null || m_Wrapper.m_DialogueActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DialogueActionsCallbackInterfaces.Add(instance);
            @Continue.started += instance.OnContinue;
            @Continue.performed += instance.OnContinue;
            @Continue.canceled += instance.OnContinue;
            @ChangeSelection.started += instance.OnChangeSelection;
            @ChangeSelection.performed += instance.OnChangeSelection;
            @ChangeSelection.canceled += instance.OnChangeSelection;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
        }

        private void UnregisterCallbacks(IDialogueActions instance)
        {
            @Continue.started -= instance.OnContinue;
            @Continue.performed -= instance.OnContinue;
            @Continue.canceled -= instance.OnContinue;
            @ChangeSelection.started -= instance.OnChangeSelection;
            @ChangeSelection.performed -= instance.OnChangeSelection;
            @ChangeSelection.canceled -= instance.OnChangeSelection;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
        }

        public void RemoveCallbacks(IDialogueActions instance)
        {
            if (m_Wrapper.m_DialogueActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDialogueActions instance)
        {
            foreach (var item in m_Wrapper.m_DialogueActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DialogueActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DialogueActions @Dialogue => new DialogueActions(this);

    // Selector
    private readonly InputActionMap m_Selector;
    private List<ISelectorActions> m_SelectorActionsCallbackInterfaces = new List<ISelectorActions>();
    private readonly InputAction m_Selector_Move;
    private readonly InputAction m_Selector_ToggleSkillWheel;
    private readonly InputAction m_Selector_Select;
    private readonly InputAction m_Selector_DeSelect;
    public struct SelectorActions
    {
        private @PlayerControls m_Wrapper;
        public SelectorActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Selector_Move;
        public InputAction @ToggleSkillWheel => m_Wrapper.m_Selector_ToggleSkillWheel;
        public InputAction @Select => m_Wrapper.m_Selector_Select;
        public InputAction @DeSelect => m_Wrapper.m_Selector_DeSelect;
        public InputActionMap Get() { return m_Wrapper.m_Selector; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SelectorActions set) { return set.Get(); }
        public void AddCallbacks(ISelectorActions instance)
        {
            if (instance == null || m_Wrapper.m_SelectorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SelectorActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @ToggleSkillWheel.started += instance.OnToggleSkillWheel;
            @ToggleSkillWheel.performed += instance.OnToggleSkillWheel;
            @ToggleSkillWheel.canceled += instance.OnToggleSkillWheel;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @DeSelect.started += instance.OnDeSelect;
            @DeSelect.performed += instance.OnDeSelect;
            @DeSelect.canceled += instance.OnDeSelect;
        }

        private void UnregisterCallbacks(ISelectorActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @ToggleSkillWheel.started -= instance.OnToggleSkillWheel;
            @ToggleSkillWheel.performed -= instance.OnToggleSkillWheel;
            @ToggleSkillWheel.canceled -= instance.OnToggleSkillWheel;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @DeSelect.started -= instance.OnDeSelect;
            @DeSelect.performed -= instance.OnDeSelect;
            @DeSelect.canceled -= instance.OnDeSelect;
        }

        public void RemoveCallbacks(ISelectorActions instance)
        {
            if (m_Wrapper.m_SelectorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISelectorActions instance)
        {
            foreach (var item in m_Wrapper.m_SelectorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SelectorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SelectorActions @Selector => new SelectorActions(this);

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Aim;
    private readonly InputAction m_Player_ToggleSkillWheel;
    private readonly InputAction m_Player_RestartLevel;
    private readonly InputAction m_Player_ToggleAiming;
    private readonly InputAction m_Player_UseAgility;
    private readonly InputAction m_Player_UseWeapon1;
    private readonly InputAction m_Player_UseWeapon2;
    private readonly InputAction m_Player_UseAbility1;
    private readonly InputAction m_Player_UseAbility2;
    private readonly InputAction m_Player_SwitchCharacterLeft;
    private readonly InputAction m_Player_SwitchCharacterRight;
    private readonly InputAction m_Player_RestartLevel1;
    private readonly InputAction m_Player_ToggleControls;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Aim => m_Wrapper.m_Player_Aim;
        public InputAction @ToggleSkillWheel => m_Wrapper.m_Player_ToggleSkillWheel;
        public InputAction @RestartLevel => m_Wrapper.m_Player_RestartLevel;
        public InputAction @ToggleAiming => m_Wrapper.m_Player_ToggleAiming;
        public InputAction @UseAgility => m_Wrapper.m_Player_UseAgility;
        public InputAction @UseWeapon1 => m_Wrapper.m_Player_UseWeapon1;
        public InputAction @UseWeapon2 => m_Wrapper.m_Player_UseWeapon2;
        public InputAction @UseAbility1 => m_Wrapper.m_Player_UseAbility1;
        public InputAction @UseAbility2 => m_Wrapper.m_Player_UseAbility2;
        public InputAction @SwitchCharacterLeft => m_Wrapper.m_Player_SwitchCharacterLeft;
        public InputAction @SwitchCharacterRight => m_Wrapper.m_Player_SwitchCharacterRight;
        public InputAction @RestartLevel1 => m_Wrapper.m_Player_RestartLevel1;
        public InputAction @ToggleControls => m_Wrapper.m_Player_ToggleControls;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @ToggleSkillWheel.started += instance.OnToggleSkillWheel;
            @ToggleSkillWheel.performed += instance.OnToggleSkillWheel;
            @ToggleSkillWheel.canceled += instance.OnToggleSkillWheel;
            @RestartLevel.started += instance.OnRestartLevel;
            @RestartLevel.performed += instance.OnRestartLevel;
            @RestartLevel.canceled += instance.OnRestartLevel;
            @ToggleAiming.started += instance.OnToggleAiming;
            @ToggleAiming.performed += instance.OnToggleAiming;
            @ToggleAiming.canceled += instance.OnToggleAiming;
            @UseAgility.started += instance.OnUseAgility;
            @UseAgility.performed += instance.OnUseAgility;
            @UseAgility.canceled += instance.OnUseAgility;
            @UseWeapon1.started += instance.OnUseWeapon1;
            @UseWeapon1.performed += instance.OnUseWeapon1;
            @UseWeapon1.canceled += instance.OnUseWeapon1;
            @UseWeapon2.started += instance.OnUseWeapon2;
            @UseWeapon2.performed += instance.OnUseWeapon2;
            @UseWeapon2.canceled += instance.OnUseWeapon2;
            @UseAbility1.started += instance.OnUseAbility1;
            @UseAbility1.performed += instance.OnUseAbility1;
            @UseAbility1.canceled += instance.OnUseAbility1;
            @UseAbility2.started += instance.OnUseAbility2;
            @UseAbility2.performed += instance.OnUseAbility2;
            @UseAbility2.canceled += instance.OnUseAbility2;
            @SwitchCharacterLeft.started += instance.OnSwitchCharacterLeft;
            @SwitchCharacterLeft.performed += instance.OnSwitchCharacterLeft;
            @SwitchCharacterLeft.canceled += instance.OnSwitchCharacterLeft;
            @SwitchCharacterRight.started += instance.OnSwitchCharacterRight;
            @SwitchCharacterRight.performed += instance.OnSwitchCharacterRight;
            @SwitchCharacterRight.canceled += instance.OnSwitchCharacterRight;
            @RestartLevel1.started += instance.OnRestartLevel1;
            @RestartLevel1.performed += instance.OnRestartLevel1;
            @RestartLevel1.canceled += instance.OnRestartLevel1;
            @ToggleControls.started += instance.OnToggleControls;
            @ToggleControls.performed += instance.OnToggleControls;
            @ToggleControls.canceled += instance.OnToggleControls;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @ToggleSkillWheel.started -= instance.OnToggleSkillWheel;
            @ToggleSkillWheel.performed -= instance.OnToggleSkillWheel;
            @ToggleSkillWheel.canceled -= instance.OnToggleSkillWheel;
            @RestartLevel.started -= instance.OnRestartLevel;
            @RestartLevel.performed -= instance.OnRestartLevel;
            @RestartLevel.canceled -= instance.OnRestartLevel;
            @ToggleAiming.started -= instance.OnToggleAiming;
            @ToggleAiming.performed -= instance.OnToggleAiming;
            @ToggleAiming.canceled -= instance.OnToggleAiming;
            @UseAgility.started -= instance.OnUseAgility;
            @UseAgility.performed -= instance.OnUseAgility;
            @UseAgility.canceled -= instance.OnUseAgility;
            @UseWeapon1.started -= instance.OnUseWeapon1;
            @UseWeapon1.performed -= instance.OnUseWeapon1;
            @UseWeapon1.canceled -= instance.OnUseWeapon1;
            @UseWeapon2.started -= instance.OnUseWeapon2;
            @UseWeapon2.performed -= instance.OnUseWeapon2;
            @UseWeapon2.canceled -= instance.OnUseWeapon2;
            @UseAbility1.started -= instance.OnUseAbility1;
            @UseAbility1.performed -= instance.OnUseAbility1;
            @UseAbility1.canceled -= instance.OnUseAbility1;
            @UseAbility2.started -= instance.OnUseAbility2;
            @UseAbility2.performed -= instance.OnUseAbility2;
            @UseAbility2.canceled -= instance.OnUseAbility2;
            @SwitchCharacterLeft.started -= instance.OnSwitchCharacterLeft;
            @SwitchCharacterLeft.performed -= instance.OnSwitchCharacterLeft;
            @SwitchCharacterLeft.canceled -= instance.OnSwitchCharacterLeft;
            @SwitchCharacterRight.started -= instance.OnSwitchCharacterRight;
            @SwitchCharacterRight.performed -= instance.OnSwitchCharacterRight;
            @SwitchCharacterRight.canceled -= instance.OnSwitchCharacterRight;
            @RestartLevel1.started -= instance.OnRestartLevel1;
            @RestartLevel1.performed -= instance.OnRestartLevel1;
            @RestartLevel1.canceled -= instance.OnRestartLevel1;
            @ToggleControls.started -= instance.OnToggleControls;
            @ToggleControls.performed -= instance.OnToggleControls;
            @ToggleControls.canceled -= instance.OnToggleControls;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Dismiss
    private readonly InputActionMap m_Dismiss;
    private List<IDismissActions> m_DismissActionsCallbackInterfaces = new List<IDismissActions>();
    private readonly InputAction m_Dismiss_Dismiss;
    public struct DismissActions
    {
        private @PlayerControls m_Wrapper;
        public DismissActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Dismiss => m_Wrapper.m_Dismiss_Dismiss;
        public InputActionMap Get() { return m_Wrapper.m_Dismiss; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DismissActions set) { return set.Get(); }
        public void AddCallbacks(IDismissActions instance)
        {
            if (instance == null || m_Wrapper.m_DismissActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DismissActionsCallbackInterfaces.Add(instance);
            @Dismiss.started += instance.OnDismiss;
            @Dismiss.performed += instance.OnDismiss;
            @Dismiss.canceled += instance.OnDismiss;
        }

        private void UnregisterCallbacks(IDismissActions instance)
        {
            @Dismiss.started -= instance.OnDismiss;
            @Dismiss.performed -= instance.OnDismiss;
            @Dismiss.canceled -= instance.OnDismiss;
        }

        public void RemoveCallbacks(IDismissActions instance)
        {
            if (m_Wrapper.m_DismissActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDismissActions instance)
        {
            foreach (var item in m_Wrapper.m_DismissActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DismissActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DismissActions @Dismiss => new DismissActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_Select;
    private readonly InputAction m_Menu_Cancel;
    public struct MenuActions
    {
        private @PlayerControls m_Wrapper;
        public MenuActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Menu_Select;
        public InputAction @Cancel => m_Wrapper.m_Menu_Cancel;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    public interface IDialogueActions
    {
        void OnContinue(InputAction.CallbackContext context);
        void OnChangeSelection(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface ISelectorActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnToggleSkillWheel(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnDeSelect(InputAction.CallbackContext context);
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnToggleSkillWheel(InputAction.CallbackContext context);
        void OnRestartLevel(InputAction.CallbackContext context);
        void OnToggleAiming(InputAction.CallbackContext context);
        void OnUseAgility(InputAction.CallbackContext context);
        void OnUseWeapon1(InputAction.CallbackContext context);
        void OnUseWeapon2(InputAction.CallbackContext context);
        void OnUseAbility1(InputAction.CallbackContext context);
        void OnUseAbility2(InputAction.CallbackContext context);
        void OnSwitchCharacterLeft(InputAction.CallbackContext context);
        void OnSwitchCharacterRight(InputAction.CallbackContext context);
        void OnRestartLevel1(InputAction.CallbackContext context);
        void OnToggleControls(InputAction.CallbackContext context);
    }
    public interface IDismissActions
    {
        void OnDismiss(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
    }
}
